### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by Cheong-96** [vss2sn/path_planning#1]
你的代码看起来写得很好，可是却有非常严重的问题。在栅格尺寸10x10情况下运行良好，可是当尺寸是20x20的时候计算严重超时，40x40更是直接中断退出。在linux服务器如此，换成windows集成开发环境也是一样，应该多看看到底哪里出了问题。

**Comment by vss2sn** [comment]
Thanks for bringing this to my attention. Believe this was overlooked during refactoring. Added back in. Feel free to test it out and reopen the issue should it recur.

**Comment by vss2sn** [comment]
Google Translate for the above comment:
Your code seems to be well written, but there is a very serious problem. It works well when the grid size is 10x10, but when the size is 20x20, the calculation times out seriously, and 40x40 directly interrupts and exits. This is the case in the Linux server, and the same is true for the Windows integrated development environment. You should see more where the problem is.
